### ISSUE TITLE
undefined TypeError: Cannot read property 'sign' of undefined

### ISSUE THREAD

**Issue by napasa** [shmy/cn-pay#4]
TypeError: Cannot read property 'sign' of undefined
    at Wechat.verify (C:\Users\Administrator\Desktop\test\node_modules\cn-pay\src\wechat\index.js:48:25)
    at app.post (C:\Users\Administrator\Desktop\test\index.js:36:16)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\Administrator\Desktop\test\node_modules\express\lib\middleware\init.js:40:5)

该错误原因有express不原生支持xml parser，因此需要插件。
对于该错误可如下方式解决：
```
const xmlparser = require('express-xml-bodyparser');
 app.post('/official_pay/tenpay_callback', xmlparser({trim: false, explicitArray: false}), function(req, res, next) {  
    if (wechat.verify(req.body.xml)) { // 一句话验签，就这么简单
        console.log("微信支付异步验签成功：");
        // 业务逻辑
        res.send(wechat.success()); // 可以调用success或fail方法 返回结果
    } else {
        console.log("微信支付异步验签失败：");
        res.send(wechat.fail("验签失败"));
    }
 }
```

**Comment by napasa** [comment]
TypeError: Cannot read property 'sign' of undefined
    at Wechat.verify (C:\Users\Administrator\Desktop\test\node_modules\cn-pay\src\wechat\index.js:48:25)
    at app.post (C:\Users\Administrator\Desktop\test\index.js:36:16)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\Administrator\Desktop\test\node_modules\express\lib\router\index.js:275:10)
    at expressInit (C:\Users\Administrator\Desktop\test\node_modules\express\lib\middleware\init.js:40:5)

**Comment by shmy** [comment]
是哪个环节

**Comment by napasa** [comment]
回调环节

**Comment by shmy** [comment]
你打印下req.body 有哪些属性

**Comment by napasa** [comment]
对回调进行答应。console.log(JSON.stringify(req.body));输出为空。
代码很简单。我生成的二维码也能正常支付。
```
app.get('/', (req, res) => {
    let date = new Date();
    const order = {
        "out_trade_no": date.yyyymmddhhminssmi(),
        "body": `蹦咔卡`,
        "total_fee": 0.01, // 直接以元为单位
        "spbill_create_ip": "127.0.0.1" // 客户端ip
    };
    wechat.scan(order).then((orderinfo) => {
		if( orderinfo.return_code === "SUCCESS" && orderinfo.result_code === "SUCCESS" ){
			res.send(orderinfo);
		}
    }).catch((exception) => {
        return res.send( exception );
    });	

});
app.post('/official_pay/tenpay_callback', ( req, res ) => {
	console.log(JSON.stringify(req.body));
    if (wechat.verify(req.body)) { // 一句话验签，就这么简单
        console.log("微信支付异步验签成功：");
        // 业务逻辑
        res.send(wechat.success()); // 可以调用success或fail方法 返回结果
    } else {
        console.log("微信支付异步验签失败：");
        res.send(wechat.fail("验签失败"));
    }

});

Date.prototype.yyyymmddhhminssmi = function() {
    "use strict";
    let mm = this.getMonth() + 1; // getMonth() is zero-based
    let dd = this.getDate();
    let hh = this.getHours();
    let min = this.getMinutes();
    let ss = this.getSeconds();
    let mi = this.getMilliseconds();

    return [ this.getFullYear(),
        ( mm > 9 ? "" : "0" ) + mm,
        ( dd > 9 ? "" : "0" ) + dd,
        ( hh > 9 ? "" : "0" ) + hh,
        ( min > 9 ? "" : "0" ) + min,
        ( ss > 9 ? "" : "0" ) + ss,
        ( mi > 99 ? "" : ( mi > 9 ? "0" : "00" ) ) + mi
    ].join( "" );
};

app.listen(80, () => console.log('Example app listening on port 80!'))
```

**Comment by napasa** [comment]
经过努力。可以打印req.body的值了，但还是不能验签
```
{"xml":{"appid":"wx6bb2581e5dc132f2","bank_type":"HXB_CREDIT","cash_fee":"1","fee_type":"CNY","is_subscribe":"Y","mch_id":"1503284251","n
once_str":"emdyad31x94","openid":"*************","out_trade_no":"20180620114427324","result_code":"SUCCESS","return_code":
"SUCCESS","sign":"*****************","time_end":"20180620114516","total_fee":"1","trade_type":"NATIVE","transaction_id":"4
200000113201806206172671025"}}
微信支付异步验签失败：
```

**Comment by shmy** [comment]
```
verify(body, sign) {
    body = typeof body === 'string' ? util.parseXML(body) : body;
    sign = sign || body.sign;
    return sign === util.generateSign(body, this.config.key);
  }
```

你打印出怎么有个xml的属性，那你传入req.body.xml试试吧

**Comment by napasa** [comment]
该错误原因有express不原生支持xml parser，因此需要插件。
对于该错误可如下方式解决：
```
const xmlparser = require('express-xml-bodyparser');
 app.post('/official_pay/tenpay_callback', xmlparser({trim: false, explicitArray: false}), function(req, res, next) {  
    if (wechat.verify(req.body.xml)) { // 一句话验签，就这么简单
        console.log("微信支付异步验签成功：");
        // 业务逻辑
        res.send(wechat.success()); // 可以调用success或fail方法 返回结果
    } else {
        console.log("微信支付异步验签失败：");
        res.send(wechat.fail("验签失败"));
    }
 }
```

**Comment by shmy** [comment]
如果body未解析，但是能拿到字符串，插件内部会自动转换的

**Comment by napasa** [comment]
不太懂。我是业余的。你看看能不能写个例子方便别人使用。
